# Generated by Django 3.2.9 on 2021-12-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20211203_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('graphic', 'Graphic Design'), ('web', 'Web Development')], max_length=255),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='service',
            field=models.CharField(choices=[('graphic', 'Graphic Design'), ('web', 'Web Development')], max_length=100),
        ),
    ]
