# Generated by Django 3.2.9 on 2021-12-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_rename_sociallinks_sociallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
