# Generated by Django 3.2.9 on 2021-12-05 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_sociallink_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sociallink',
            old_name='facebook',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='mail',
        ),
    ]
