# Generated by Django 3.2.9 on 2021-12-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_contact_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectImage',
            field=models.ImageField(upload_to='media/our_work'),
        ),
    ]
