# Generated by Django 4.0 on 2021-12-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_alter_project_projectimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_photo', models.ImageField(upload_to='image/client')),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(max_length=255)),
                ('client_business', models.CharField(max_length=255)),
                ('client_product', models.CharField(choices=[('Logo', 'Logo'), ('Flyer', 'Flyer'), ('Broucher', 'Broucher'), ('Templates', 'Templates'), ('Web Design', 'Web Design'), ('Print Design', 'Print Design'), ('Visiting Card', 'Visiting Card'), ('Website Development', 'Website Development')], max_length=255)),
                ('client_review', models.TextField()),
                ('review_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
