# Generated by Django 4.0 on 2021-12-31 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_clientreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientreview',
            old_name='client_photo',
            new_name='product_photo',
        ),
        migrations.RemoveField(
            model_name='clientreview',
            name='client_business',
        ),
    ]
