# Generated by Django 4.0 on 2021-12-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_rename_client_photo_clientreview_product_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientreview',
            name='client_business',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
