# Generated by Django 4.0 on 2021-12-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_clientreview_client_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='service',
            field=models.CharField(choices=[('Logo', 'Logo'), ('Flyer', 'Flyer'), ('Broucher', 'Broucher'), ('Templates', 'Templates'), ('Web Design', 'Web Design'), ('Print Design', 'Print Design'), ('Visiting Card', 'Visiting Card'), ('Website Development', 'Website Development')], max_length=100),
        ),
    ]
