# Generated by Django 4.0 on 2022-01-01 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_alter_quotation_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientreview',
            old_name='product_photo',
            new_name='client_photo',
        ),
        migrations.RenameField(
            model_name='clientreview',
            old_name='client_product',
            new_name='client_services',
        ),
    ]
