# Generated by Django 4.0 on 2022-01-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_rename_product_photo_clientreview_client_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(choices=[('Logo', 'Logo'), ('Flyer', 'Flyer'), ('Broucher', 'Broucher'), ('Templates', 'Templates'), ('Web Design', 'Web Design'), ('Print Design', 'Print Design'), ('Visiting Card', 'Visiting Card'), ('Website Development', 'Website Development')], max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='quotation',
            name='quantity',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
