# Generated by Django 4.0 on 2022-01-03 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_alter_clientreview_client_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientreview',
            name='client_photo',
        ),
    ]
