# Generated by Django 4.0 on 2022-01-03 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_remove_clientreview_client_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientreview',
            name='review_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
