# Generated by Django 4.1 on 2022-09-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0028_alter_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('Graphic Design', 'design'), ('Web Development', 'web-dev')], max_length=255),
        ),
    ]
