# Generated by Django 4.1 on 2022-09-16 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0029_alter_category_category_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quotation',
        ),
    ]
