# Generated by Django 4.1 on 2022-10-02 11:11

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0030_delete_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientreview',
            name='projectImage',
            field=models.ImageField(default=1, upload_to='', verbose_name=portfolio.models.Project),
            preserve_default=False,
        ),
    ]
