# Generated by Django 4.1 on 2022-10-02 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0031_clientreview_projectimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
