# Generated by Django 4.1 on 2022-12-09 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0032_alter_project_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client_business',
        ),
        migrations.RemoveField(
            model_name='project',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='project',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='projectImage',
        ),
    ]
