# Generated by Django 4.1 on 2022-12-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0033_remove_project_client_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('design', 'Graphic Design'), ('website', 'Web Development')], max_length=255),
        ),
    ]
